[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

# Enable Netlify Functions (if needed for future enhancements)
[functions]
  directory = "netlify/functions"